#sudo sysctl -w vm.max_map_count=262144

version: '3.6'
services:
  suricata:
    image: "msanz741/suricata_mario"
    container_name: suricata_es3
    privileged: true
    command: -i br-9150db277ae9
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    network_mode: "host"
    volumes:
      - ../../escenarios/escenario3/logstash/pipeline:/var/log/suricata
      - ../../../../suricata_config:/etc/suricata


